### ISSUE TITLE
Show server version.

### ISSUE THREAD

**Issue by cybershambles** [imrehg/twbankssl#16]
IIS/Apache/nginx whatever.

**Comment by imrehg** [comment]
There's a testing patch on the serversig brannch (commit f6e27c2c24d59e2124621127d3aab0b2cbc4962f).

It would need some visual tweaking for sure. Also, while it is interesting information, does not have direct bearing on the quality of the websites (unlike the grade and the vulnerabilities), so I'd need to think whether to add to the display in general (whether it's helpful or confusing overall). But if you want to use it, the patch is there!
