### ISSUE TITLE
"ValueError: too many values to unpack" - Large amount of domains in server.cvs

### ISSUE THREAD

**Issue by cybershambles** [imrehg/twbankssl#19]
I've tried running this check on 850 domains. This has failed.

**Comment by imrehg** [comment]
Yeah, I've tested it with <50.

Can put the server list CSV up to pastebin or something similar? The scanning script needs a rethink anyways, there should be better ways of doing batches of long running jobs.

**Comment by cybershambles** [comment]
https://raw.githubusercontent.com/HTTPSWatchAU/Easteregg/master/servers.csv

**Comment by imrehg** [comment]
At least `runjobs.py` runs okay for me here, though I presume it will take a few hours to check all the details.

Would be very helpful if you'd tell a bit more about the error you get. Which script, what settings, what's the full output (python errors usually show the line number too)? Without that it's difficult to say anything.

**Comment by imrehg** [comment]
My job running on the same list finished correctly (about 3 hours to run), and the output json is generated as well. http://pastebin.com/ebZkMZ2w thus so far I cannot replicate the error

**Comment by cybershambles** [comment]
Thanks for investigating. I've found the cause of the original issue was a mistake with the CSV.

This is a false alarm. I'm running the job now on my server.
